CREATE TABLE IF NOT EXISTS "public"."indicadores" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "colaborador" text NOT NULL,
    "data" text NOT NULL,
    "dados_json" text NOT NULL,
    "criado_em" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE "public"."indicadores" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir acesso total indicadores" ON "public"."indicadores";

CREATE POLICY "Permitir acesso total indicadores"
ON "public"."indicadores"
USING (true)
WITH CHECK (true);

GRANT ALL ON TABLE "public"."indicadores" TO "anon";
GRANT ALL ON TABLE "public"."indicadores" TO "authenticated";
GRANT ALL ON TABLE "public"."indicadores" TO "service_role";
