CREATE TABLE IF NOT EXISTS "public"."acervo_mapa_posicoes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sala" text NOT NULL DEFAULT '',
    "tipo" text NOT NULL DEFAULT 'modulo_deslizante',
    "numero" text NOT NULL DEFAULT '',
    "numero_estante" text NOT NULL DEFAULT '',
    "prateleiras" integer NOT NULL DEFAULT 1,
    "capacidade_por_prateleira" integer NOT NULL DEFAULT 1,
    "caixas_ocupadas" integer NOT NULL DEFAULT 0,
    "prateleiras_ocupacao" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "caixas_cores" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "cor_setor" text NOT NULL DEFAULT '#0ea5e9',
    "observacao" text NOT NULL DEFAULT '',
    "criado_em" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "atualizado_em" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."acervo_mapa_setores" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" text NOT NULL DEFAULT '',
    "cor" text NOT NULL DEFAULT '#0ea5e9',
    "criado_em" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_acervo_mapa_posicoes_sala"
ON "public"."acervo_mapa_posicoes" ("sala");

CREATE INDEX IF NOT EXISTS "idx_acervo_mapa_posicoes_tipo"
ON "public"."acervo_mapa_posicoes" ("tipo");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_acervo_mapa_setores_cor_unique"
ON "public"."acervo_mapa_setores" (lower("cor"));

ALTER TABLE "public"."acervo_mapa_posicoes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."acervo_mapa_setores" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir acesso total mapa posicoes" ON "public"."acervo_mapa_posicoes";
DROP POLICY IF EXISTS "Permitir acesso total mapa setores" ON "public"."acervo_mapa_setores";

CREATE POLICY "Permitir acesso total mapa posicoes"
ON "public"."acervo_mapa_posicoes"
USING (true)
WITH CHECK (true);

CREATE POLICY "Permitir acesso total mapa setores"
ON "public"."acervo_mapa_setores"
USING (true)
WITH CHECK (true);

GRANT ALL ON TABLE "public"."acervo_mapa_posicoes" TO "anon";
GRANT ALL ON TABLE "public"."acervo_mapa_posicoes" TO "authenticated";
GRANT ALL ON TABLE "public"."acervo_mapa_posicoes" TO "service_role";

GRANT ALL ON TABLE "public"."acervo_mapa_setores" TO "anon";
GRANT ALL ON TABLE "public"."acervo_mapa_setores" TO "authenticated";
GRANT ALL ON TABLE "public"."acervo_mapa_setores" TO "service_role";
